# SPDX-License-Identifier: GPL-3.0-or-later
"""Installing and removing this, for the current user.

Everything lands under a per-user prefix and nothing needs root. That is
deliberate rather than modest: Bazzite is rpm-ostree, so /usr is read-only and
anything layered there has to survive every rebase. A per-user prefix survives
that, and uninstalling is deleting files rather than unpicking a package. The
same holds for any immutable system, which is most of where Sunshine gets
installed from Flathub.

Windows will not use this. It has no such convention, and the decision recorded
in docs/backlog.md is to install as a normal Windows application instead.
"""

import os
import shutil
import subprocess
import sys
from typing import List, Optional, Tuple

from . import legacy
from . import places

# What is needed to run. Tests, git history and build files are not.
INSTALLED = ("src", "assets", "scripts", "docs", "README.md", "LICENSE",
             "LICENSE.upstream-MIT", "NOTICE")

COMMAND = "sunshine-apps-ui"


def default_prefix() -> str:
    return os.getenv("PREFIX") or places.programs_home()


def paths(prefix: Optional[str] = None):
    prefix = prefix or default_prefix()
    if os.name == "nt":
        # No share/bin split: Windows keeps a program in one directory, and the
        # thing you run sits in it. A .cmd rather than an extensionless file,
        # because Windows decides what is executable by extension.
        import ntpath
        install = ntpath.join(prefix, "sunshine-apps-ui")
        return {
            "prefix": prefix,
            "install": install,
            "bin": install,
            "command": ntpath.join(install, COMMAND + ".cmd"),
            "state": places.state_dir(),
        }
    return {
        "prefix": prefix,
        "install": os.path.join(prefix, "share", "sunshine-apps-ui"),
        "bin": os.path.join(prefix, "bin"),
        "command": os.path.join(prefix, "bin", COMMAND),
        "state": places.state_dir(),
    }


def _source_root() -> str:
    """The checkout this is being installed from."""
    return os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__))))


def _launcher_script(install_dir: str) -> str:
    """A tiny entry point, so the installed command is a real program.

    It does nothing but put the installed copy on the path and hand over, which
    keeps "what runs" in Python rather than in whatever shell happens to exist.
    """
    return (
        "#!/usr/bin/env python3\n"
        "# SPDX-License-Identifier: GPL-3.0-or-later\n"
        '"""Run the installed copy of sunshine-apps-ui."""\n'
        "import os, sys\n"
        f"sys.path.insert(0, {os.path.join(install_dir, 'src')!r})\n"
        "from sunshine_apps_ui.__main__ import main\n"
        "raise SystemExit(main())\n"
    )


def _windows_launcher(install_dir: str) -> str:
    """The installed command, as a .cmd.

    Windows has no shebang, so the entry point is a batch file that puts the
    installed copy on PYTHONPATH and hands over. It finds an interpreter rather
    than hard-coding one, because the one that ran the installer may not be the
    one on PATH afterwards -- and until this ships an interpreter of its own
    (issue #9), whichever is there has to do.
    """
    import ntpath
    source = ntpath.join(install_dir, "src")
    ours = ntpath.join(install_dir, "python", "python.exe")
    return (
        "@echo off\r\n"
        "rem sunshine-apps-ui. Generated by the installer; edits will be lost.\r\n"
        "rem Run from somewhere else: --uninstall deletes the directory this\r\n"
        "rem file is in, and cmd.exe complains on its way out if that is also\r\n"
        "rem where it is standing. Uninstalling from Add/Remove Programs should\r\n"
        "rem not end with an error about a path.\r\n"
        'cd /d "%TEMP%"\r\n'
        "rem The interpreter we shipped comes first: it is the one this was\r\n"
        "rem tested against, and the only one guaranteed to be here at all. It\r\n"
        "rem reads its own ._pth and ignores PYTHONPATH, which is set below for\r\n"
        "rem the fallbacks rather than for it.\r\n"
        f'set "PYTHONPATH={source};%PYTHONPATH%"\r\n'
        f'if exist "{ours}" (\r\n'
        f'  "{ours}" -m sunshine_apps_ui %*\r\n'
        ") else (\r\n"
        "  where py >nul 2>&1\r\n"
        "  if %errorlevel%==0 (\r\n"
        "    py -3 -m sunshine_apps_ui %*\r\n"
        "  ) else (\r\n"
        "    python -m sunshine_apps_ui %*\r\n"
        "  )\r\n"
        ")\r\n"
    )


# Where Windows lists what is installed. Per-user, because this installs
# per-user: HKCU is what "Apps & features" reads for a per-user program, and it
# needs no administrator to write.
UNINSTALL_KEY = r"Software\Microsoft\Windows\CurrentVersion\Uninstall\sunshine-apps-ui"


def windowless_command(where) -> str:
    """How to start the interface with no console window anywhere.

    A .cmd always opens one, and pythonw.exe never does. Sean, seeing the
    result of the .cmd: "closing the gui windows left the console launch helper
    open. This cannot happen. There needs to be one window."

    The .cmd stays: it is the right entry point for a terminal, where --scan and
    --uninstall are run and their output is the point.
    """
    if os.name != "nt":
        return where["command"]
    # os.path for the existence check -- it has to be a path this filesystem can
    # open, and on Windows the two modules are the same one anyway.
    quiet = os.path.join(where["install"], "python", "pythonw.exe")
    if os.path.isfile(quiet):
        return f'"{quiet}" -m sunshine_apps_ui'
    return f'"{where["command"]}"'


# Sunshine's own entry on Bazzite, read off the machine:
#   Categories=RemoteAccess;Network;
#   Keywords=gamestream;stream;moonlight;remote play;
# Sean's instruction: sit in the same category as Sunshine, so the two are
# found together rather than this turning up under "Other".
DESKTOP_CATEGORIES = "RemoteAccess;Network;"
DESKTOP_KEYWORDS = "sunshine;gamestream;moonlight;apps;games;"
DESKTOP_FILE = "sunshine-apps-ui.desktop"


def _icon_files(where) -> dict:
    """Square icons for the menus, derived from the artwork already shipped.

    `assets/poster.png` is the picture Sunshine shows on the tile -- portrait,
    because a tile is portrait. A menu wants a square, so the tiles at the top
    of it are cropped out. Nothing is designed here: a new icon is issue #20,
    and when it lands this picks it up by dropping `assets/icon.png` in beside
    the poster.

    Pillow does the work, and Pillow is not on every Linux machine. Without it
    there is simply no icon, which costs a menu entry its picture and nothing
    else.
    """
    assets = os.path.join(where["install"], "assets")
    chosen = os.path.join(assets, "icon.png")
    made = {}
    try:
        from PIL import Image
    except ImportError:
        return {"png": chosen if os.path.isfile(chosen) else ""}

    source = chosen if os.path.isfile(chosen) else os.path.join(assets, "poster.png")
    if not os.path.isfile(source):
        return {}
    try:
        with Image.open(source) as art:
            art = art.convert("RGBA")
            side = min(art.size)
            # The top square: on the shipped poster that is the grid of tiles,
            # with the caption below it left out.
            square = art.crop((0, 0, side, side)).resize((256, 256),
                                                         Image.LANCZOS)
            png = os.path.join(assets, "menu-icon.png")
            square.save(png)
            made["png"] = png
            if os.name == "nt":
                ico = os.path.join(assets, "menu-icon.ico")
                square.save(ico, sizes=[(16, 16), (24, 24), (32, 32),
                                        (48, 48), (64, 64), (128, 128),
                                        (256, 256)])
                made["ico"] = ico
    except Exception:                    # noqa: BLE001 - a picture, not the program
        return {}
    return made


def _desktop_entry(where) -> List[str]:
    """The Linux equivalent of the Start menu shortcut.

    A `.desktop` file in the per-user applications directory, which every
    desktop reads: KDE on Bazzite, GNOME, and anything else that follows the
    freedesktop menu specification. No root, nothing outside `~`.
    """
    if os.name == "nt":
        return []
    applications = os.path.join(places.data_home(), "applications")
    try:
        os.makedirs(applications, exist_ok=True)
    except OSError as e:
        return [f"No menu entry: {applications} could not be made ({e})."]

    icon = _icon_files(where).get("png", "")
    path = os.path.join(applications, DESKTOP_FILE)
    entry = "\n".join([
        "[Desktop Entry]",
        "Type=Application",
        "Version=1.0",
        "Name=Sunshine App Manager",
        "GenericName=Game library manager",
        "Comment=Manage the apps Sunshine offers",
        f"Exec={where['command']}",
        f"Icon={icon or 'applications-games'}",
        "Terminal=false",
        f"Categories={DESKTOP_CATEGORIES}",
        f"Keywords={DESKTOP_KEYWORDS}",
        "StartupNotify=true",
        "",
    ])
    try:
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(entry)
        os.chmod(path, 0o644)
    except OSError as e:
        return [f"No menu entry: {path} could not be written ({e})."]

    # Politely ask the desktop to notice. Absent on a minimal install, and its
    # absence only means the entry appears at the next login instead.
    updater = shutil.which("update-desktop-database")
    if updater:
        try:
            subprocess.run([updater, applications], capture_output=True,
                           timeout=30)
        except (OSError, subprocess.SubprocessError):
            pass
    return [f"Menu entry    {path}"]


def _remove_desktop_entry() -> List[str]:
    if os.name == "nt":
        return []
    path = os.path.join(places.data_home(), "applications", DESKTOP_FILE)
    if os.path.isfile(path) and _remove(path):
        return ["Removed the menu entry."]
    return []


def _start_menu_shortcut(where) -> str:
    """A way to open it at the machine, not only from a stream.

    Sean, on using it: "we need a way to launch it locally too from the start
    menu I think." Without one, the only way to open it on the machine in front
    of you is to type the path to a .cmd that is not on PATH.

    Made with a WScript shell object through PowerShell: a .lnk is a structured
    file, not something to write by hand, and this is the one way to make one
    that needs nothing installed.
    """
    if os.name != "nt":
        return ""
    programs = os.path.join(
        os.environ.get("APPDATA", ""), "Microsoft", "Windows",
        "Start Menu", "Programs")
    if not os.path.isdir(programs):
        return ""
    link = os.path.join(programs, "Sunshine App Manager.lnk")
    # A .lnk cannot take a .png: Windows wants an .ico or a binary with icon
    # resources, and a PNG here left the shortcut showing pythonw's snake.
    icon = _icon_files(where).get("ico", "")
    # pythonw, so opening this from the Start menu produces one window: the
    # interface. A .cmd target puts a console beside it that outlives nothing
    # and confuses everything.
    quiet = os.path.join(where["install"], "python", "pythonw.exe")
    if os.path.isfile(quiet):
        target, arguments = quiet, "-m sunshine_apps_ui"
    else:
        target, arguments = where["command"], ""
    script = (
        "$shell = New-Object -ComObject WScript.Shell; "
        f"$link = $shell.CreateShortcut('{link}'); "
        f"$link.TargetPath = '{target}'; "
        f"$link.Arguments = '{arguments}'; "
        f"$link.WorkingDirectory = '{where['install']}'; "
        "$link.Description = 'Manage the apps Sunshine offers'; "
        + (f"$link.IconLocation = '{icon}'; " if os.path.isfile(icon) else "")
        + "$link.Save()")
    try:
        result = subprocess.run(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command", script],
            capture_output=True, timeout=30,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    except (OSError, subprocess.SubprocessError):
        return ""
    return link if result.returncode == 0 and os.path.isfile(link) else ""


def _remove_start_menu_shortcut() -> List[str]:
    if os.name != "nt":
        return []
    link = os.path.join(os.environ.get("APPDATA", ""), "Microsoft", "Windows",
                        "Start Menu", "Programs", "Sunshine App Manager.lnk")
    if os.path.isfile(link) and _remove(link):
        return ["Removed the Start menu shortcut."]
    return []


def _register_with_windows(where) -> List[str]:
    """Appear in Add/Remove Programs, like any other installed program.

    Without this the only way to remove it is to know the command, which is not
    how anyone expects to uninstall something on Windows.
    """
    if os.name != "nt":
        return []
    import winreg

    from .version import display, version

    command = where["command"]
    try:
        size = 0
        for root, _dirs, files in os.walk(where["install"]):
            for name in files:
                try:
                    size += os.path.getsize(os.path.join(root, name))
                except OSError:
                    continue
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, UNINSTALL_KEY) as key:
            winreg.SetValueEx(key, "DisplayName", 0, winreg.REG_SZ,
                              "Sunshine App Manager")
            winreg.SetValueEx(key, "DisplayVersion", 0, winreg.REG_SZ, version())
            winreg.SetValueEx(key, "Publisher", 0, winreg.REG_SZ, "4o66")
            winreg.SetValueEx(key, "InstallLocation", 0, winreg.REG_SZ,
                              where["install"])
            winreg.SetValueEx(key, "UninstallString", 0, winreg.REG_SZ,
                              f'"{command}" --uninstall')
            winreg.SetValueEx(key, "QuietUninstallString", 0, winreg.REG_SZ,
                              f'"{command}" --uninstall')
            winreg.SetValueEx(key, "NoModify", 0, winreg.REG_DWORD, 1)
            winreg.SetValueEx(key, "NoRepair", 0, winreg.REG_DWORD, 1)
            winreg.SetValueEx(key, "EstimatedSize", 0, winreg.REG_DWORD,
                              max(1, size // 1024))
            winreg.SetValueEx(key, "URLInfoAbout", 0, winreg.REG_SZ,
                              "https://github.com/4o66/sunshine-apps-ui")
    except OSError as e:
        return [f"Could not register in Add/Remove Programs: {e}"]
    return [f"Listed in Add/Remove Programs as Sunshine App Manager ({display()})"]


def _deferred_removal(install_dir: str) -> str:
    """Delete the install once this process is gone, not from inside it."""
    # One string, not a list. A list is quoted argument by argument, which
    # wraps the whole thing in quotes that already contain quotes -- cmd then
    # parses none of it and silently does nothing, which is how this failed the
    # first time: no error, and the directory still there.
    command = (f'cmd.exe /c ping -n 3 127.0.0.1 >nul & '
               f'rmdir /s /q "{install_dir}"')
    try:
        subprocess.Popen(
            command,
            creationflags=(getattr(subprocess, "CREATE_NO_WINDOW", 0)
                           | getattr(subprocess, "DETACHED_PROCESS", 0)),
            close_fds=True)
    except (OSError, subprocess.SubprocessError) as e:
        return f"Could not remove {install_dir}: {e}. Delete it by hand."
    return f"Removing {install_dir} as this exits."


def _unregister_with_windows() -> List[str]:
    if os.name != "nt":
        return []
    import winreg
    try:
        winreg.DeleteKey(winreg.HKEY_CURRENT_USER, UNINSTALL_KEY)
    except FileNotFoundError:
        return []
    except OSError as e:
        return [f"Could not remove the Add/Remove Programs entry: {e}"]
    return ["Removed the Add/Remove Programs entry."]


def _provide_interpreter(where, wanted: Optional[bool], confirm=None) -> List[str]:
    """Put a Python beside the program, so the machine does not need one.

    Asked rather than assumed when there is a terminal: it is a download, from
    the internet, onto somebody's machine. Declining is a real answer -- the
    command falls back to whatever Python is on PATH, which is exactly the
    situation on a developer's box.
    """
    if os.name != "nt":
        return []
    from . import interpreter

    # A working one is left alone even when asked for again. Replacing it means
    # deleting it, and deleting an interpreter that something is still running
    # from leaves a broken one -- which is exactly what happened on the rig.
    existing = interpreter.bundled_python(where["install"])
    if existing and interpreter.works(existing):
        return ["Interpreter already installed and working; leaving it alone."]
    if existing:
        return ["", f"The interpreter at {existing} does not run. Replacing it.",
                *_replace_interpreter(where, interpreter)]
    if wanted is False:
        return ["Skipped the interpreter, as asked. The command will use "
                "whatever Python is on PATH."]
    if wanted is None:
        question = ("Install a Python interpreter alongside it? Windows does "
                    "not come with one, and without it this only runs where "
                    "Python happens to be.")
        detail = "\n".join(["This would download:"] + interpreter.describe())
        if confirm is None:
            return ["", "No interpreter was installed: this was not asked "
                        "interactively. Run --install --with-interpreter to add "
                        "one, or --without-interpreter to say so deliberately.",
                    "Until then the command needs a Python on PATH."]
        if not confirm(detail, question):
            return ["Skipped the interpreter. The command will use whatever "
                    "Python is on PATH."]

    try:
        interpreter.provision(where["install"], log=lambda line: None)
    except interpreter.ProvisionError as e:
        # Not fatal: everything else is installed and works wherever a Python
        # exists. Saying exactly what failed matters more than failing.
        return ["", f"The interpreter was not installed: {e}",
                "Everything else is in place; the command will use whatever "
                "Python is on PATH."]
    return [f"Interpreter   {os.path.join(where['install'], 'python', 'python.exe')}"]


def _provide_window(where) -> List[str]:
    """Build the WebView2 window, if this machine can have one.

    Never fatal, and never asked about. Unlike the interpreter this is not a
    choice between working and not working: the browser path is there either
    way, so a machine that cannot build this simply keeps what it had. What is
    worth saying is which one it ended up with, because that is the difference
    between the app appearing in a second and a half and in three and a half.
    """
    if os.name != "nt":
        return _provide_window_linux()
    from . import winhost

    if not winhost.runtime_version():
        return ["Window        a browser (no WebView2 runtime on this machine)"]
    if winhost.is_current(where["install"]):
        return ["Window        already built and working; leaving it alone."]
    if not winhost.compiler():
        return ["Window        a browser (no C# compiler found; it is normally "
                "part of Windows)"]
    try:
        winhost.build(where["install"], log=lambda line: None)
    except Exception as e:                   # noqa: BLE001 - never fail install
        return ["", f"The app window was not built: {e}",
                "Everything else is installed; this machine will use a browser."]
    return [f"Window        {os.path.join(where['install'], 'host', 'AppWindow.exe')}"]


def _provide_window_linux() -> List[str]:
    """Say which window this machine will use, and how to get the better one.

    Nothing is installed here: on Linux that is the package manager's business
    and root's, and this install needs neither. But which window you get is
    worth knowing, and on Debian and Ubuntu it turns on two packages nobody
    would guess at -- the WebKitGTK library alone leaves no typelib, so the
    manager quietly uses a browser on a machine that could do better.
    """
    if os.name == "nt":
        return []
    from . import gtkhost

    if gtkhost.toolkit_present() and not gtkhost.sandbox_can_run():
        # The toolkit is here and would work but for the machine's policy.
        # Saying which policy matters: without it this reads as "your distro
        # is unsupported", and it is not -- it is one switch.
        return ["Window        a browser (WebKitGTK's sandbox cannot start "
                "here)",
                "              unprivileged user namespaces are restricted on "
                "this system, which",
                "              WebKitGTK requires. Ubuntu 24.04 does this by "
                "default."]
    if gtkhost.toolkit_present():
        return ["Window        our own (GTK 4 + WebKitGTK)"]
    how = gtkhost.how_to_install()
    return ["Window        a browser (no GTK 4 / WebKitGTK typelibs here)",
            f"              for a faster window: {how}"]


def _replace_interpreter(where, interpreter) -> List[str]:
    try:
        interpreter.provision(where["install"], log=lambda line: None)
    except interpreter.ProvisionError as e:
        return [f"It could not be replaced: {e}"]
    return ["Replaced it."]


def install(prefix: Optional[str] = None, *,
            with_interpreter: Optional[bool] = None,
            confirm=None) -> Tuple[bool, List[str]]:
    """Copy this into place. Returns (installed, messages)."""
    where = paths(prefix)
    messages = []

    blocking = legacy.destructive_installs()
    if blocking:
        # The original rewrites apps.json from scratch on every run, removing
        # everything it did not generate. It cannot be left beside this, so
        # this is a refusal rather than a warning.
        messages.append("The original bazzite-sunshine-manager is still installed:")
        for found in blocking:
            messages.append(f"  {found['root']}")
            for path in legacy.removal_plan(found):
                messages.append(f"    would remove: {path}")
        messages.append("")
        messages.append(legacy.REWRITES_EVERYTHING)
        messages.append("")
        messages.append(legacy.SUNSHINE_WEB_UI)
        if confirm is None or not confirm(
                "\n".join(messages),
                "Remove it? Only its own files; apps.json is not touched."):
            messages.append("")
            messages.append("Left in place. Do not run it: it will undo what this "
                            "manages. Nothing was installed.")
            return False, messages
        for found in blocking:
            for path in legacy.removal_plan(found):
                messages.append(f"  removed {path}" if _remove(path)
                                else f"  could not remove {path}")

    source = _source_root()
    os.makedirs(where["install"], exist_ok=True)
    os.makedirs(where["bin"], exist_ok=True)

    for item in INSTALLED:
        origin = os.path.join(source, item)
        if not os.path.exists(origin):
            continue
        target = os.path.join(where["install"], item)
        _remove(target)
        if os.path.isdir(origin):
            shutil.copytree(origin, target,
                            ignore=shutil.ignore_patterns("__pycache__"))
        else:
            shutil.copy2(origin, target)

    # An installed copy has no git to ask, so the answer is written down while
    # the checkout that has one is still to hand. Without this every install
    # would report build 0 and every bug report would be ambiguous.
    stamp_build(os.path.join(where["install"], "src", "sunshine_apps_ui"))

    with open(where["command"], "w", encoding="utf-8") as handle:
        handle.write(_windows_launcher(where["install"]) if os.name == "nt"
                     else _launcher_script(where["install"]))
    if os.name != "nt":
        os.chmod(where["command"], 0o755)

    messages.append(f"Installed to {where['install']}")
    messages.append(f"Command     {where['command']}")
    messages.extend(_provide_interpreter(where, with_interpreter, confirm))
    messages.extend(_provide_window(where))
    messages.extend(_desktop_entry(where))
    shortcut = _start_menu_shortcut(where)
    if shortcut:
        messages.append(f"Start menu   {shortcut}")
    messages.extend(_register_with_windows(where))

    messages.extend(_offer_unhide_tile(confirm))

    on_path = [os.path.normpath(p) for p in os.getenv("PATH", "").split(os.pathsep)]
    if os.path.normpath(where["bin"]) not in on_path:
        messages.append("")
        messages.append(f"Note: {where['bin']} is not on your PATH. Sunshine's tile "
                        f"still works -- it runs the command by its full path -- "
                        f"but you cannot type it.")
    return True, messages


def _offer_unhide_tile(confirm=None) -> List[str]:
    """Offer to bring back a tile that was hidden rather than merely deleted.

    A deleted tile comes back on its own: nothing records the deletion, so the
    next scan sees the launcher as new and adds it. A *hidden* one does not --
    hiding writes a tombstone, and a tombstone is an instruction to keep
    skipping it, which --put-the-tile-back-because-i-deleted-it obeys along
    with everything else. So reinstalling to get the tile back quietly achieves
    nothing, and the only clue is a tile that never reappears.

    Asking is the point. The tombstone is a decision the user made, and an
    installer that silently reversed it would be no better than one that
    silently ignored it.
    """
    try:
        from .core import api
    except ImportError:                          # pragma: no cover - defensive
        return []
    try:
        conf_dir = api.config_dir()
        hidden = [t for t in api.state(conf_dir).get("hidden") or []
                  if t.get("source") == "launcher" and t.get("id") == "apps-ui"]
    except Exception:                            # noqa: BLE001 - not worth failing an install
        return []
    if not hidden:
        return []

    name = hidden[0].get("name") or "The manager's own tile"
    question = (f"{name} is hidden, so scanning will keep skipping it. "
                f"Put it back?")
    if confirm is None:
        # Non-interactive: say so rather than decide. Reversing a hide without
        # being asked is exactly what the tombstone exists to prevent.
        return ["", f"Note: {name} is hidden, so it will not come back on its "
                    f"own -- not even with --put-the-tile-back-because-i-deleted-it. "
                    f"Unhide it from the app list, or reinstall where you can "
                    f"answer a prompt."]
    if not confirm("", question):
        return ["", f"Left hidden. {name} stays out of Sunshine until you "
                    f"unhide it."]

    try:
        ok, message, _ = api.mutate(
            conf_dir, [{"op": "restore", "selector": "launcher:apps-ui"}])
    except Exception as e:                       # noqa: BLE001 - reported
        return ["", f"Could not unhide {name}: {e}"]
    if not ok:
        return ["", f"Could not unhide {name}: {message}"]

    # Hiding keeps the whole entry, so restoring puts the tile straight back.
    # Suppressing -- refusing something a scan offered, before it ever existed
    # in the file -- has no entry to put back, so clearing the tombstone only
    # stops it being skipped. Saying "unhid" and leaving no tile would look
    # exactly like the silent failure this was written to remove.
    if _tile_is_present(api, conf_dir):
        return ["", f"Unhid {name}."]
    return ["", f"Unhid {name}, but there was no kept copy of it to put back. "
                f"Run --install --put-the-tile-back-because-i-deleted-it to "
                f"rebuild it; nothing is blocking it now."]


def _tile_is_present(api, conf_dir: str) -> bool:
    try:
        return any(a.get("source") == "launcher" and a.get("id") == "apps-ui"
                   for a in api.state(conf_dir).get("apps") or [])
    except Exception:                            # noqa: BLE001 - defensive
        return True                              # do not invent bad news


def stamp_build(package_dir: str) -> bool:
    """Write down which build this is, for a copy that cannot work it out.

    Refuses to replace a known build number with an unknown one. Installing
    from a source tree that has no git -- an unpacked tarball, say -- would
    otherwise overwrite a number carried in that tarball with 0, which is the
    exact ambiguity this exists to prevent.
    """
    from .version import details

    found = details(refresh=True)
    target = os.path.join(package_dir, "_build.py")
    if found["build"] in ("", "0") and os.path.exists(target):
        return False
    try:
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(
                "# SPDX-License-Identifier: GPL-3.0-or-later\n"
                '"""Written when this was packaged or installed. Not in git:\n'
                'it describes one copy, not the source it came from."""\n'
                f"BUILD = {found['build']!r}\n"
                f"COMMIT = {found['commit']!r}\n"
                f"DIRTY = {bool(found['dirty'])!r}\n")
        return True
    except OSError:
        return False              # a missing build number is not worth failing over


def _remove_browser_task() -> List[str]:
    """Take back the scheduled task the Windows launcher registers.

    It exists because a task at RunLevel Limited is the one way measured to
    start a medium-integrity process from an elevated one. Leaving a task behind
    after an uninstall would be litter on somebody's machine.
    """
    if os.name != "nt":
        return []
    from .winbrowser import TASK_NAME
    try:
        result = subprocess.run(
            ["schtasks", "/delete", "/tn", TASK_NAME, "/f"],
            capture_output=True, timeout=30,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    except (OSError, subprocess.SubprocessError):
        return [f"Could not remove the scheduled task {TASK_NAME}; remove it by hand."]
    if result.returncode == 0:
        return [f"Removed the scheduled task {TASK_NAME}."]
    return []            # it was never registered, which is the usual case


def uninstall(prefix: Optional[str] = None, *, keep_state: bool = False,
              keep_tile: bool = False,
              purge_backups: bool = False) -> Tuple[bool, List[str]]:
    """Remove this, tile included. Returns (removed, messages)."""
    where = paths(prefix)
    messages = []

    from .launcher import stop_previous
    stop_previous()
    messages.extend(_remove_browser_task())
    messages.extend(_unregister_with_windows())
    messages.extend(_remove_start_menu_shortcut())
    messages.extend(_remove_desktop_entry())

    if not keep_tile:
        # The tile goes first, while the engine is still installed to remove it
        # properly. Deleting our files first would leave a tile pointing at a
        # command that no longer exists.
        removed, note = _remove_tile()
        messages.append(note)
        if not removed:
            messages.append("Leaving the files in place.")
            return False, messages

    if os.name == "nt":
        # Removing the directory we are running out of works, but cmd.exe reads
        # a .cmd line by line and goes back for the next one after Python
        # returns -- so uninstalling from Add/Remove Programs ended with "The
        # system cannot find the path specified." after it had already said
        # Done. Hand the deletion to a detached command that waits for us to
        # exit first. Nothing is left running, and nothing complains.
        messages.append(_deferred_removal(where["install"]))
    else:
        _remove(where["command"])
        _remove(where["install"])
        messages.append(f"Removed {where['install']}")

    backups = os.path.join(where["state"], "backups")
    if keep_state:
        messages.append(f"Kept {where['state']}")
    elif purge_backups:
        _remove(where["state"])
        messages.append(f"Removed {where['state']}, kept copies included")
    else:
        # Everything under state except the copies of apps.json, which are
        # copies of your configuration rather than of this program -- and an
        # uninstall is a moment you might want one back.
        for name in _listdir(where["state"]):
            if name != "backups":
                _remove(os.path.join(where["state"], name))
        kept = len(_listdir(backups))
        if kept:
            messages.append(f"Kept {backups} ({kept} copies of apps.json)")
            messages.append("  Remove them with --purge-backups, or by hand.")

    messages.append("Done. Sunshine, and everything in apps.json that was not "
                    "ours, is untouched.")
    return True, messages


def _remove_tile() -> Tuple[bool, str]:
    """Delete this manager's own tile, by its marker rather than its name."""
    try:
        from .core import api
    except ImportError as e:                     # pragma: no cover - defensive
        return False, f"Could not load the engine to remove the tile: {e}"
    try:
        conf_dir = api.config_dir()
        found = [a for a in api.state(conf_dir).get("apps") or []
                 if a.get("source") == "launcher" and a.get("id") == "apps-ui"]
    except Exception as e:                       # noqa: BLE001 - reported
        return False, f"Could not read the app list: {e}"
    if not found:
        return True, "No tile to remove; it is not in apps.json."
    entry = found[0]
    try:
        ok, message, _ = api.mutate(
            conf_dir, [{"op": "delete", "index": entry["index"],
                        "name": entry["name"]}])
    except Exception as e:                       # noqa: BLE001 - reported
        return False, f"Could not remove the tile: {e}"
    return ok, (message if ok else f"Could not remove the tile: {message}")


def _listdir(path: str) -> List[str]:
    try:
        return sorted(os.listdir(path))
    except OSError:
        return []


def _remove(path: str) -> bool:
    try:
        if os.path.islink(path) or os.path.isfile(path):
            os.remove(path)
        elif os.path.isdir(path):
            shutil.rmtree(path)
        return True
    except OSError:
        return False
