# SPDX-License-Identifier: GPL-3.0-or-later
"""Running a scan and reconciling the result into apps.json.

This is the part that was `main()` in the standalone importer. The flags it
read from the environment are now an options mapping, so the same code serves a
command line and a caller in this process -- which is the whole point of
folding the two projects together.

Derived from MIT-licensed work by wadiebs. See NOTICE.
"""

import os
import re
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

from .reconcile import (MARKER, SCHEMA_VERSION, backup, log_plan, plan_document,
                        reconcile)
from .artwork_sources import load_sgdb_key
from .system_apps import find_system_apps_json, load_system_apps, restore_missing
from .sunshine_api import reload_sunshine
from .utils import log, read_json, write_json
from .sources.steam import import_steam
from .sources.heroic import import_heroic
from .sources.launchers import import_launchers

VERSION = "2.0+4o66.0.1.0"
UPSTREAM_VERSION = "2.0"
FORK_VERSION = "0.1.0"
UPSTREAM = "wadiebs/bazzite-sunshine-manager 2.0 (4bedee5, 2026-04-19)"

# What we stamp into apps.json, and every name this file has been written under.
# Reading must accept the old ones: an apps.json written before the two projects
# were folded together says the old name, and it is still ours -- forgetting that
# would make us treat our own entries as somebody else's and leave them alone
# forever.
GENERATED_BY = "sunshine-apps-ui"
GENERATED_BY_ANY = (GENERATED_BY, "bazzite-sunshine-manager")


def _flag(opts: Dict[str, Any], name: str, default: bool) -> bool:
    value = opts.get(name)
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def _selectors(value: str) -> List[str]:
    """Parse a comma/space separated list of <source>:<id> selectors."""
    return [t for t in re.split(r"[,\s]+", str(value or "").strip()) if t]


def execute(conf_dir: str, opts: Optional[Dict[str, Any]] = None,
            home: Optional[str] = None) -> Dict[str, Any]:
    """Scan, reconcile, and write unless asked not to. Returns the plan document."""
    opts = dict(opts or {})
    home = home or str(Path.home())
    dry_run = _flag(opts, "BSM_DRY_RUN", False)

    # Paths
    apps_json = os.path.join(conf_dir, "apps.json")
    images_root = os.path.join(conf_dir, "images")
    images_dir_steam = os.path.join(images_root, "steam")
    images_dir_heroic = os.path.join(images_root, "heroic")
    images_dir_sideload = os.path.join(images_root, "sideload")
    for d in (images_dir_steam, images_dir_heroic, images_dir_sideload):
        os.makedirs(d, exist_ok=True)

    log(f"Sunshine config: {conf_dir}")
    log(f"Images root:     {images_root}")

    # Load what is already there. Entries we did not generate are preserved.
    payload = read_json(apps_json, {})
    if not isinstance(payload, dict):
        payload = {"apps": payload if isinstance(payload, list) else []}
    existing_apps = payload.get("apps")
    if not isinstance(existing_apps, list):
        existing_apps = []

    # Files written by older versions of this tool have no ownership markers, but
    # were a wholesale rewrite, so every entry in them is ours. Adopt by name.
    meta = payload.get("meta")
    adopt_by_name = (
        isinstance(meta, dict)
        and meta.get("generated-by") in GENERATED_BY_ANY
        and not any(isinstance(a, dict) and MARKER in a for a in existing_apps)
    )
    if adopt_by_name:
        log("Existing apps.json was generated by an older version; adopting entries by name.")

    refresh = _selectors(opts.get("BSM_REFRESH_EDITED", ""))
    if refresh:
        log(f"Refreshing user-edited fields for: {', '.join(refresh)}")

    # Sunshine's own defaults. Seed a fresh config from them, and put them back
    # on request if an older version of this tool rewrote them away.
    include_system = _flag(opts, "INCLUDE_SYSTEM_APPS", True)
    restore_defaults = _flag(opts, "BSM_RESTORE_DEFAULTS", False)
    system_apps: list = []
    if include_system:
        system_path = find_system_apps_json(str(opts.get("SYSTEM_APPS_JSON", "")).strip())
        if system_path:
            system_apps = load_system_apps(system_path)
            log(f"Sunshine defaults: {len(system_apps)} entries from {system_path}")
        else:
            log("Sunshine defaults: shipped apps.json not found; skipping.")

    if system_apps and not existing_apps:
        existing_apps = [dict(a) for a in system_apps]
        log(f"Fresh config: seeded with {len(existing_apps)} Sunshine default entries.")
    elif system_apps and restore_defaults:
        existing_apps, restored = restore_missing(existing_apps, system_apps)
        if restored:
            log(f"Restored Sunshine defaults: {', '.join(restored)}")
        else:
            log("Restore defaults: all default entries already present.")
    restore_removed = _selectors(opts.get("BSM_RESTORE_REMOVED", ""))
    prune = _flag(opts, "BSM_REMOVE_UNINSTALLED", False)
    allow_empty_prune = _flag(opts, "BSM_ALLOW_EMPTY_PRUNE", False)

    # What we wrote last run, and what the user has deleted since. Both live in
    # the "meta" block of apps.json, which Sunshine preserves: saveApp() and
    # deleteApp() only ever rewrite file_tree["apps"].
    prior = meta if isinstance(meta, dict) else {}
    previously_managed = prior.get("managed") if isinstance(prior.get("managed"), list) else []
    tombstones = prior.get("removed") if isinstance(prior.get("removed"), list) else []

    # Read toggles from environment
    IMPORT_STEAM = _flag(opts, "IMPORT_STEAM", True)
    IMPORT_HEROIC = _flag(opts, "IMPORT_HEROIC", True)

    enabled_importers = []
    if IMPORT_STEAM:
        enabled_importers.append("steam")
    if IMPORT_HEROIC:
        enabled_importers.append("heroic")

    settings: Dict[str, Any] = dict(os.environ)
    settings.update({k: v for k, v in opts.items() if v not in (None, "")})
    # A key stored by --save-sgdb-key serves a scan as well as the picker, and
    # keeps it out of argv, where --sgdb-key puts it.
    if not str(settings.get("SGDB_API_KEY", "")).strip():
        settings["SGDB_API_KEY"] = load_sgdb_key(conf_dir)

    # Collect apps from enabled importers, recording how each one fared. A source
    # that raised is not the same as a source that found nothing, and consumers
    # need to tell them apart before acting on "missing" entries.
    apps: list = []
    sources: list = []

    def run_source(name: str, enabled: bool, fn):
        report: Dict[str, Any] = {"name": name, "enabled": enabled,
                                  "status": "disabled", "imported": 0}
        sources.append(report)
        if not enabled:
            log(f"{name.capitalize()} importer disabled.")
            return
        try:
            found = fn(report) or []
        except Exception as e:                       # noqa: BLE001 - reported, not swallowed
            log(f"{name.capitalize()} importer failed: {e}")
            report["status"] = "error"
            report["error"] = str(e)
            return
        apps.extend(found)
        report["imported"] = len(found)

    run_source("steam", IMPORT_STEAM,
               lambda r: import_steam(home, conf_dir, images_dir_steam, settings, r))
    run_source("heroic", IMPORT_HEROIC,
               lambda r: import_heroic(home, conf_dir, images_dir_heroic, settings, r))
    run_source("launcher", True,
               lambda r: import_launchers(home, conf_dir,
                                          os.path.join(conf_dir, "images", "launchers"),
                                          settings, r))

    # Only a source that actually read its library may have entries pruned. A
    # source that could not be found looks exactly like one whose games were all
    # uninstalled, and acting on that deletes a library that is merely offline.
    prunable: list = []
    if prune:
        for report in sources:
            name, status = report["name"], report.get("status")
            if status != "ok":
                log(f"Not removing {name} entries: scan status is {status!r}, "
                    f"which does not prove anything was uninstalled.")
            elif not report.get("imported") and not allow_empty_prune:
                log(f"Not removing {name} entries: it scanned cleanly but returned "
                    f"nothing, which usually means a library is offline or mid-update. "
                    f"Pass --allow-empty-prune if everything really was uninstalled.")
            else:
                prunable.append(name)

    # --- ENV BLOCK FIRST ---
    # Default PATH augmentation as requested; allow optional extra append via ENV_PATH_APPEND.
    env_block = {
        "PATH": "$(PATH):$(HOME)/.local/bin" + ((":" + opts.get("ENV_PATH_APPEND")) if opts.get("ENV_PATH_APPEND") else "")
    }

    from .sources.launchers import FORMER_NAMES

    merged_apps, plan = reconcile(existing_apps, apps,
                                  former_names={
                                      was: ("launcher", key)
                                      for was, key in FORMER_NAMES.items()},
                                  adopt_by_name=adopt_by_name, refresh=refresh,
                                  previously_managed=previously_managed,
                                  tombstones=tombstones,
                                  prunable_sources=prunable,
                                  restore_removed=restore_removed)
    log_plan(plan)

    if dry_run:
        log("Dry run: apps.json not written.")
    elif os.path.exists(apps_json):
        try:
            log(f"Backup saved: {backup(apps_json)}")
        except Exception as e:
            log(f"Warning: failed to backup apps.json: {e}")

    # "env" first, then "apps", preserving any other top-level keys the user has.
    out = {"env": payload.get("env", env_block), "apps": merged_apps}
    for key, value in payload.items():
        if key not in ("env", "apps", "meta"):
            out[key] = value
    out["meta"] = {
        "generated-by": GENERATED_BY,
        "enabled-importers": enabled_importers,
        "managed": plan.get("managed", []),
        "removed": plan.get("tombstones", []),
    }
    if not dry_run:
        write_json(apps_json, out)
        log(f"Wrote {len(merged_apps)} apps ({len(plan['kept_foreign'])} not ours, left alone). "
            f"Enabled importers: {', '.join(enabled_importers) or 'none'}")

    # Sunshine has no file watcher, so the file we just wrote is invisible to it
    # until it re-reads. Ask it to, rather than restarting and dropping whatever
    # stream is in progress.
    if not dry_run and _flag(opts, "BSM_RELOAD", False):
        reload_sunshine(conf_dir)

    return plan_document(plan, config_dir=conf_dir, apps_json=apps_json,
                         sources=sources, dry_run=dry_run,
                         generator_version=VERSION,
                         fork="4o66/bazzite-sunshine-manager",
                         upstream=UPSTREAM)

